version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      modelado_net:
        ipv4_address: '192.168.1.101'
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.100
      KAFKA_ZOOKEEPER_CONNECT: 192.168.1.101:2181
      KAFKA_CREATE_TOPICS: "respuesta:4:2,operaciones:4:2:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      modelado_net:
        ipv4_address: '192.168.1.100'
  redis: 
    image: rchicangana/redis:v1
    ports:
      - 6379:6379
    networks:
      modelado_net:
        ipv4_address: '192.168.1.2'
  redisservice: 
    image: rchicangana/redisservice:v1
    ports:
      - 9191:8080
    networks:
      modelado_net:
        ipv4_address: '192.168.1.3'
    depends_on:
      - redis
  suscriptionservice: 
    image: rchicangana/suscriptionservice:v1
    ports:
      - 9292:8080
    expose: 
      - "9292"
    networks:
      modelado_net:
        ipv4_address: '192.168.1.6'
    depends_on:
      - redis
      - redisservice
  operationservice: 
    image: rchicangana/operationservice:v1
    ports:
      - 9393:8080
    expose: 
      - "9393"
    networks:
      modelado_net:
        ipv4_address: '192.168.1.4'
    depends_on:
      - redis
      - redisservice
  intermediateroutingservice: 
    image: rchicangana/intermediateroutingservice:v1
    ports:
      - 9494:8080
    networks:
      modelado_net:
        ipv4_address: '192.168.1.5'
    depends_on:
      - redis
      - redisservice
      - kafka     
      
networks:
  modelado_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
     
